### mostrar todas las especies
GET http://localhost:3080/api/especies

### traer una especie en concreto
GET http://localhost:3080/api/especies/6535e7c490491933002ea601

### crear una especie
POST http://localhost:3080/api/especies
Content-Type: application/json

{
    "descripcion": "Felino"
        
}

### modificar una especie
PUT http://localhost:3080/api/especies/65453a040a3f65743cef8710
Content-Type: application/json

{       
        "descripcion": "Ave"
}


### eliminar una especie
DELETE http://localhost:3080/api/especies/65453a260a3f65743cef8711