### obtener todos los usuarios
GET http://localhost:3080/api/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNlYWVjZDMyODlhM2YzODVhNmFiNCIsImVtYWlsIjoiY2FsYW1icmVAZ21haWwuY29tIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzI5NTM2NzU1LCJleHAiOjE3Mjk1Mzc2NTV9.jOEqJT7p2ujTnaetWYRBscwLKfDqfW9Ik40fd8qf6ws


### Obtener un usuario
GET http://localhost:3080/api/usuarios/656a327befec9ec6f30760de

### Enviar un nuevo usuario
POST http://localhost:3080/api/usuarios
Content-Type: application/json

{
    "nombre": "Admin",
    "apellido": "Admin",
    "email": "admin@admin.com", 
    "password": "Password1",
    "telefono": "1111111111",
    "nro_doc": "11111111",
    "direccion": "MongoDB 112",
    "rol": "65334d8d48ec52ff5e08c85a"
}

### modificar un usuario - PUT
PUT  http://localhost:3080/api/usuarios/656a327befec9ec6f30760de
Content-Type: application/json

{
    "rol": "65334d6048ec52ff5e08c859"
}


### eliminar un usuario 
DELETE http://localhost:3080/api/usuarios/6533480f1c7d492e38aca24a