### obtener todos los usuarios
GET http://localhost:3080/api/usuarios

### Obtener un usuario
GET http://localhost:3080/api/usuarios/653347dd1c7d492e38aca249

### Enviar un nuevo usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre": "Patalia",
    "apellido": "Neluso",
    "email": "calambres@gmail.com", 
    "password": "Password1",
    "telefono": "198997919",
    "nro_doc": "4276728",
    "direccion": "Buenos Aires 6179",
    "rol": "65334d8d48ec52ff5e08c85a"
}

### modificar un usuario - PUT
PUT  http://localhost:3000/api/usuarios/653347dd1c7d492e38aca249
Content-Type: application/json

{
    "rol": "65334d8d48ec52ff5e08c85a"
}


### eliminar un usuario 
DELETE http://localhost:3000/api/usuarios/6533480f1c7d492e38aca24a