### mostrar todas las prácticas
GET http://localhost:3080/api/practicas

### traer una práctica en concreto
GET http://localhost:3080/api/practicas/65579fc4fd003fd4159c4592

### crear una práctica
POST http://localhost:3080/api/practicas
Content-Type: application/json

{
    "descripcion": "Castración"
        
}

### modificar una práctica
PUT http://localhost:3080/api/practicas/65677edf5da64c13c3780206
Content-Type: application/json

{       
        "descripcion": "Consulta general"
}

### modificar una práctica
PATCH  http://localhost:3080/api/practicas/6535e1dcc3f120197defbe02
Content-Type: application/json

{       
        "descripcion": "Consulta general"
}

### eliminar una práctica
DELETE http://localhost:3080/api/practicas/6535e20ec3f120197defbe04