### mostrar todas las prácticas
GET http://localhost:3080/api/precios

### traer una práctica en concreto
GET http://localhost:3080/api/precios/6535e1dcc3f120197defbe02

### crear una práctica
POST http://localhost:3080/api/precios
Content-Type: application/json

{
    "fecha": "2024-12-23",
    "valor": 12720,
    "practica": "656a051fb0461301a47c67e5"
        
}

### modificar una práctica
PUT http://localhost:3080/api/precios/6545b26bcc196071e8e597bf
Content-Type: application/json

{       
    "fecha": "2023-08-03",
    "valor": 900
}

### eliminar una práctica
DELETE http://localhost:3080/api/precios/6545b26bcc196071e8e597bf