### mostrar todos los veterinarios
GET http://localhost:3000/api/veterinarios

### traer un solo veterinario
GET http://localhost:3000/api/veterinarios/566ase

### crear un veterinario
POST http://localhost:3000/api/veterinarios
Content-Type: application/json

{
        "id_veterinario":"0056as",
        "matricula":"3535445ZZ",
        "apellido":"Coulee",
        "nombre":"Shae",
        "direccion":"Queenzlay 356",
        "telefono":3456565335,
        "email":"shaecoulee@gmail.com",
        "password":"ihatethatbaldguy01",
        "tipo_doc":"dni",
        "nro_doc":65874521,
        "sexo":"masculino"
}

### modificar un veterinario
PUT http://localhost:3000/api/veterinarios/566ase
Content-Type: application/json

{
        "id_veterinario":"566ase",
        "matricula":"7777445ZZ",
        "apellido":"Dixon",
        "nombre":"Daryl",
        "direccion":"Caminito 556",
        "telefono":345881115,
        "email":"daryldixon@gmail.com",
        "password":"walkerskiller7000",
        "tipo_doc":"dni",
        "nro_doc":33544521,
        "sexo":"masculino"
}

### modificar un veterinario
PATCH  http://localhost:3000/api/veterinarios/566ase
Content-Type: application/json

{
        "apellido":"Dario",
        "nombre":"Dixoso",
        "direccion":"North Highway 658",
        "email":"daryonldix@gmail.com"
}

### eliminar un veterinario
DELETE http://localhost:3000/api/veterinarios/566ase