### mostrar todos los veterinarios
GET http://localhost:3080/api/veterinarios

### traer un solo veterinario
GET http://localhost:3080/api/veterinarios/6533f156ec66df25f176150f

### crear un veterinario
POST http://localhost:3080/api/veterinarios
Content-Type: application/json

{
        "matricula":"353845ZZ",
        "apellido":"Coulee",
        "nombre":"Shae",
        "telefono":"345865335",
        "email":"shaec8ulee@gmail.com",
        "password":"ihatethatbaldguy01",
        "nro_doc":"65884521",
        "rol":"65334db548ec52ff5e08c85b"
}

### modificar un veterinario
PUT http://localhost:3080/api/veterinarios/6533f26d059dedfac38f97ac
Content-Type: application/json

{
        "matricula":"7777445ZZ",
        "apellido":"Dixon",
        "nombre":"Daryl",
        "telefono":"345881115",
        "email":"daryldixon@gmail.com",
        "password":"walkerskiller7000",
        "nro_doc":"33544521"
}


### eliminar un veterinario
DELETE http://localhost:3080/api/veterinarios/6533f2bdde367cdb2a479f33