### probar el token
GET http://localhost:3080/arr
Authorization: Bearer *****

### POST
POST http://localhost:3080/api/auth/login
Content-Type: application/json

{
    "email": "calambre@gmail.com", 
    "password": "Password1"
}

